### ISSUE TITLE
Fail to fetch API

### ISSUE THREAD

**Issue by stiveuk** [AbmSourav/bdapis#10]
please check your Heroku API link, it's don't work. Maybe your Heroku server paused. it's say
 **application error**

> An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command

`Heroku logs --tail`
![error heroku](https://user-images.githubusercontent.com/81069722/198875816-e108cf89-9881-4960-b530-cfffc3557f3f.PNG)

**Comment by AbmSourav** [comment]
The server has been changed. Now BD API also has its own domain.
Please update the rest API URL to https://bdapis.com/
For more details please visit: https://bdapis.com/

**Comment by stiveuk** [comment]
thanks
