### ISSUE TITLE
Your Heroku server currently not working

### ISSUE THREAD

**Issue by stiveuk** [AbmSourav/bdapis#11]
Please change the server, your Heroku server is currently paid. so please change the hosting server.

**Comment by AbmSourav** [comment]
The server has been changed. Now BD API also has it's own domain.
Please update the rest API URL to `https://bdapis.com/`
For more details please visit: https://bdapis.com/

**Comment by me-sajib** [comment]
Thank you so much.

**Comment by stiveuk** [comment]
> The server has been changed. Now BD API also has its own domain. Please update the rest API URL to `https://bdapis.com/` For more details please visit: https://bdapis.com/
thank you so much
